server:
  url: ${SERVER_URL}
  port: 8083
  servlet:
    context-path: /api

spring:
  application:
    name: top
  profiles:
    active: dev
    include: oauth


logging:
  file:
    name: /home/ubuntu/myapp.log
  level:
    com.ssafy.top: INFO


